### PR TITLE
Fix dropdown on attachment management page

### LINKED ISSUE #585: Manage documents: Menu for redacted documents does not open
Steps to reproduce:

1. Navigate to "manage documents" with an (already) redacted document.
2. Click on the arrow button behind the redacted document.
**Expected behavior:** A menu opens with entries like "Delete", "Redact".
**Actual behavior:** Menu does _not_ open.

submenu

Additional information:

- Browser: Firefox 104.0.2 (64-Bit)
- Other Menus open when clicked.

### PR DESCRIPTION
**Pull request by stefanw**
Fixes #585

### CODE REVIEW

File: frontend/javascript/components/docupload/file-review.vue [hunk 1]
```diff
@@ -119,10 +119,9 @@ export default {
   },
   mounted() {
     if (this.hasSubMenu) {
-      // eslint-disable-next-line no-new
-      new Dropdown(
-        document.getElementById(`docupload-dropdown-${this.attachment.id}`)
-      )
+      window.setTimeout(() => {
```
Comment (krmax44) [inline frontend/javascript/components/docupload/file-review.vue:122]: why the timeout? for me, it works without it

Comment (stefanw) [reply frontend/javascript/components/docupload/file-review.vue:122]: Indeed!
